# Setting up a Python environment and pre-commit.

# Unix or MacOS:
# >>> python3 -m venv venv
# >>> source venv/bin/activate

# Windows:
# >>> python -m venv venv
# >>> venv\Scripts\activate.bat

# >>> pip install --upgrade pip
# >>> pip install pre-commit
# >>> pre-commit install
# >>> pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
        - id: trailing-whitespace
          files: \.kt$
        - id: end-of-file-fixer
          files: \.kt$
        - id: check-yaml

  - repo: https://github.com/to-sta/spdx-checker-pre-commit
    rev: 0.1.5
    hooks:
      - id: spdx-license-checker
        name: run spdx-checker license check
        args: [-l, GPL-3.0-or-later]
        types_or: [kotlin]

  - repo: local
    hooks:
        - id: formatKotlin
          name: formatKotlin
          entry: sh -c './gradlew formatKotlin'
          language: system
          types: [kotlin]
          files: \.kt$

        - id: ktlint
          name: ktlint
          entry: sh -c './gradlew lintKotlin'
          language: system
          types: [kotlin]
          files: \.kt$

        - id: detekt
          name: detekt
          entry: sh -c './gradlew detekt'
          language: system
          types: [kotlin]
          files: \.kt$
